version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  network-server:
    build:
      context: ./apps/network/server
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
      NEST_PORT: ${NEST_PORT}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres
    volumes:
      - ./apps/network/server:/app
      - /app/node_modules

  network-client:
    build:
      context: ./apps/network/client
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: ${API_URL}
      NEXT_PUBLIC_CHAT_SOCKET_URL: ${CHAT_SOCKET_URL}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: development
    depends_on:
      - network-server
    volumes:
      - ./apps/network/client:/app
      - /app/node_modules
      - /app/.next

  game-client:
    build:
      context: ./apps/game
      dockerfile: client/Dockerfile
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: ${API_URL}
      VITE_GAME_SOCKET_URL: ${GAME_SOCKET_URL}
      VITE_CHAT_SOCKET_URL: ${CHAT_SOCKET_URL}
      NODE_ENV: development
    depends_on:
      - game-server
    volumes:
      - ./apps/game:/app
      - /app/client/node_modules

  game-server:
    build:
      context: ./apps/game
      dockerfile: server/Dockerfile
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      PORT: ${GAME_SERVER_PORT}
      API_URL: ${API_URL}
    volumes:
      - ./apps/game:/app
      - /app/server/node_modules

volumes:
  postgres_data:
