packages:
  - "apps/*/*"

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@prisma/engines"
  - "@scarf/scarf"
  - bcrypt
  - esbuild
  - prisma
  - unrs-resolver
  - "@swc/core"
  - msgpackr-extract
  - sharp
